### ISSUE TITLE
Notebook mentions tokenizer in readme but readme does not

### ISSUE THREAD

**Issue by gflood-kx** [KxSystems/kdbai-samples#55]
pdf_qFlat_Search.ipynb mentions the following however this information is missing from [the Readme.md file](https://github.com/KxSystems/kdbai-samples/blob/main/README.md)

![image](https://github.com/user-attachments/assets/3cc662c4-b289-4ef3-b720-27001244891b)

**Comment by RyanSieglerKX** [comment]
PR merged resolving this
